In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.model_selection import RandomizedSearchCV
from sklearn.tree import DecisionTreeRegressor
from xgboost import XGBRegressor
from catboost import CatBoostRegressor
import warnings

In [4]:
df=pd.read_csv('stud.csv')

In [5]:
## independent and dependent variables
x=df.drop(columns=['math_score'],axis=1)

In [6]:
x

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,74
1,female,group C,some college,standard,completed,90,88
2,female,group B,master's degree,standard,none,95,93
3,male,group A,associate's degree,free/reduced,none,57,44
4,male,group C,some college,standard,none,78,75
...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,99,95
996,male,group C,high school,free/reduced,none,55,55
997,female,group C,high school,free/reduced,completed,71,65
998,female,group D,some college,standard,completed,78,77
999,female,group D,some college,free/reduced,none,86,86

In [7]:
y=df['math_score']

In [8]:
y

0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math_score, Length: 1000, dtype: int64

In [9]:
x.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,74
1,female,group C,some college,standard,completed,90,88
2,female,group B,master's degree,standard,none,95,93
3,male,group A,associate's degree,free/reduced,none,57,44
4,male,group C,some college,standard,none,78,75

In [10]:
## create a column transfprmer with 3 types of transformers
x_num=x.select_dtypes(exclude="object").columns
x_cat=x.select_dtypes(include="object").columns

In [11]:
x_num

Index(['reading_score', 'writing_score'], dtype='object')

In [12]:
x_cat

Index(['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch',
       'test_preparation_course'],
      dtype='object')

In [13]:
x_num.shape

(2,)

In [14]:
x_cat.shape

(5,)

In [15]:
num_transformer=StandardScaler()
oh_transformer=OneHotEncoder()
preprocessor = ColumnTransformer([
    ("onehot", oh_transformer, x_cat),
    ("num", num_transformer, x_num),
])

In [16]:
x=preprocessor.fit_transform(x)

In [17]:
x.shape

(1000, 19)

In [18]:
x

array([[ 1.        ,  0.        ,  0.        , ...,  1.        ,
         0.19399858,  0.39149181],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         1.42747598,  1.31326868],
       [ 1.        ,  0.        ,  0.        , ...,  1.        ,
         1.77010859,  1.64247471],
       ...,
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         0.12547206, -0.20107904],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         0.60515772,  0.58901542],
       [ 1.        ,  0.        ,  0.        , ...,  1.        ,
         1.15336989,  1.18158627]])

In [19]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [20]:
x_train.shape,x_test.shape

((800, 19), (200, 19))

In [21]:
### crate an evaluaate function to give all metrics after model training
def evaluate_model(true,predicted):
    mae=mean_absolute_error(true,predicted)
    mse=mean_squared_error(true,predicted)
    r2=r2_score(true,predicted)
    return mae,mse,r2

In [22]:
## create the models list
from sklearn.ensemble import RandomForestRegressor
models = {
    "Linear Regression": LinearRegression(),
    "Lasso": Lasso(),
    "Ridge": Ridge(),
    "AdaBoost Regressor": AdaBoostRegressor(),
    "CatBoost Regressor": CatBoostRegressor(),
    "XGB Regressor": XGBRegressor(),
    "KNeighbors Regressor": KNeighborsRegressor(),
    "DecisionTree Regressor": DecisionTreeRegressor(),
    "Random Forest Regressor": RandomForestRegressor(),
}

In [23]:
models

{'Linear Regression': LinearRegression(),
 'Lasso': Lasso(),
 'Ridge': Ridge(),
 'AdaBoost Regressor': AdaBoostRegressor(),
 'CatBoost Regressor': CatBoostRegressor(loss_function='RMSE'),
 'XGB Regressor': XGBRegressor(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...),
 'KNeighbors Regressor': KNeighborsRegressor(),
 'DecisionTree Regressor': DecisionTreeRegressor(),
 'Random Forest Regressor': RandomForestRegressor()}

In [31]:
model_list=[]
r2_list=[]
for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(x_train,y_train)
    y_train_predicted=model.predict(x_train)
    y_test_predict=model.predict(x_test)

Learning rate set to 0.039525
0:	learn: 14.5987177	total: 21.2ms	remaining: 21.2s
1:	learn: 14.2251886	total: 22.5ms	remaining: 11.2s
2:	learn: 13.8866124	total: 23.5ms	remaining: 7.8s
3:	learn: 13.5235688	total: 24.5ms	remaining: 6.1s
4:	learn: 13.1887021	total: 25.5ms	remaining: 5.08s
5:	learn: 12.9124226	total: 26.4ms	remaining: 4.38s
6:	learn: 12.6000335	total: 27.4ms	remaining: 3.88s
7:	learn: 12.3299057	total: 28.3ms	remaining: 3.51s
8:	learn: 12.0660619	total: 34.3ms	remaining: 3.78s
9:	learn: 11.7730981	total: 36ms	remaining: 3.56s
10:	learn: 11.4922764	total: 38.2ms	remaining: 3.43s
11:	learn: 11.2626483	total: 40.5ms	remaining: 3.34s
12:	learn: 11.0426039	total: 42.5ms	remaining: 3.23s
13:	learn: 10.7991693	total: 48.9ms	remaining: 3.44s
14:	learn: 10.5541002	total: 50.6ms	remaining: 3.32s
15:	learn: 10.3191811	total: 53ms	remaining: 3.26s
16:	learn: 10.1000444	total: 55ms	remaining: 3.18s
17:	learn: 9.8945567	total: 56.1ms	remaining: 3.06s
18:	learn: 9.6901741	total: 57.1ms	remaining: 2.95s
19:	learn: 9.5060349	total: 58.9ms	remaining: 2.88s
20:	learn: 9.3385246	total: 60.6ms	remaining: 2.83s
21:	learn: 9.1702033	total: 63.3ms	remaining: 2.81s
22:	learn: 9.0103000	total: 64.3ms	remaining: 2.73s
23:	learn: 8.8438667	total: 65.2ms	remaining: 2.65s
24:	learn: 8.6905481	total: 66ms	remaining: 2.57s
25:	learn: 8.5553077	total: 67.1ms	remaining: 2.51s
26:	learn: 8.4138513	total: 67.8ms	remaining: 2.44s
27:	learn: 8.2925602	total: 68.7ms	remaining: 2.38s
28:	learn: 8.1621938	total: 69.4ms	remaining: 2.32s
29:	learn: 8.0407363	total: 70ms	remaining: 2.26s
30:	learn: 7.9212203	total: 71.5ms	remaining: 2.23s
31:	learn: 7.8095890	total: 72.5ms	remaining: 2.19s
32:	learn: 7.6996758	total: 74.1ms	remaining: 2.17s
33:	learn: 7.6064527	total: 74.9ms	remaining: 2.13s
34:	learn: 7.4988803	total: 75.6ms	remaining: 2.08s
35:	learn: 7.4011587	total: 76.2ms	remaining: 2.04s
36:	learn: 7.3064311	total: 76.9ms	remaining: 2s
37:	learn: 7.2238635	total: 77.5ms	remaining: 1.96s
38:	learn: 7.1434777	total: 78.2ms	remaining: 1.93s
39:	learn: 7.0628171	total: 79ms	remaining: 1.9s
40:	learn: 6.9907934	total: 79.8ms	remaining: 1.86s
41:	learn: 6.9318622	total: 80.7ms	remaining: 1.84s
42:	learn: 6.8582966	total: 81.4ms	remaining: 1.81s
43:	learn: 6.7862682	total: 82.2ms	remaining: 1.78s
44:	learn: 6.7171185	total: 83.4ms	remaining: 1.77s
45:	learn: 6.6529481	total: 84.9ms	remaining: 1.76s
46:	learn: 6.5896861	total: 86ms	remaining: 1.74s
47:	learn: 6.5312831	total: 86.8ms	remaining: 1.72s
48:	learn: 6.4713680	total: 87.7ms	remaining: 1.7s
49:	learn: 6.4164814	total: 89.8ms	remaining: 1.71s
50:	learn: 6.3698708	total: 91.5ms	remaining: 1.7s
51:	learn: 6.3256781	total: 92.3ms	remaining: 1.68s
52:	learn: 6.2757661	total: 93ms	remaining: 1.66s
53:	learn: 6.2247740	total: 93.7ms	remaining: 1.64s
54:	learn: 6.1822493	total: 94.4ms	remaining: 1.62s
55:	learn: 6.1399042	total: 95ms	remaining: 1.6s
56:	learn: 6.1005255	total: 95.7ms	remaining: 1.58s
57:	learn: 6.0625686	total: 96.5ms	remaining: 1.57s
58:	learn: 6.0305593	total: 99.4ms	remaining: 1.59s
59:	learn: 5.9979314	total: 101ms	remaining: 1.58s
60:	learn: 5.9641038	total: 102ms	remaining: 1.57s
61:	learn: 5.9337297	total: 103ms	remaining: 1.55s
62:	learn: 5.9019327	total: 103ms	remaining: 1.54s
63:	learn: 5.8737278	total: 104ms	remaining: 1.52s
64:	learn: 5.8464857	total: 105ms	remaining: 1.51s
65:	learn: 5.8206309	total: 105ms	remaining: 1.49s
66:	learn: 5.7936462	total: 106ms	remaining: 1.48s
67:	learn: 5.7653886	total: 107ms	remaining: 1.46s
68:	learn: 5.7470739	total: 108ms	remaining: 1.45s
69:	learn: 5.7223152	total: 108ms	remaining: 1.44s
70:	learn: 5.6999706	total: 109ms	remaining: 1.43s
71:	learn: 5.6827326	total: 110ms	remaining: 1.42s
72:	learn: 5.6635258	total: 110ms	remaining: 1.4s
73:	learn: 5.6423816	total: 112ms	remaining: 1.4s
74:	learn: 5.6214048	total: 114ms	remaining: 1.4s
75:	learn: 5.6024601	total: 115ms	remaining: 1.39s
76:	learn: 5.5873376	total: 115ms	remaining: 1.38s
77:	learn: 5.5723930	total: 116ms	remaining: 1.37s
78:	learn: 5.5584258	total: 117ms	remaining: 1.36s
79:	learn: 5.5415189	total: 117ms	remaining: 1.35s
80:	learn: 5.5261573	total: 118ms	remaining: 1.34s
81:	learn: 5.5117470	total: 118ms	remaining: 1.33s
82:	learn: 5.5049750	total: 119ms	remaining: 1.31s
83:	learn: 5.4939805	total: 119ms	remaining: 1.3s
84:	learn: 5.4807455	total: 120ms	remaining: 1.29s
85:	learn: 5.4640520	total: 121ms	remaining: 1.28s
86:	learn: 5.4491437	total: 122ms	remaining: 1.27s
87:	learn: 5.4382554	total: 122ms	remaining: 1.27s
88:	learn: 5.4259279	total: 123ms	remaining: 1.26s
89:	learn: 5.4123312	total: 124ms	remaining: 1.25s
90:	learn: 5.4006915	total: 124ms	remaining: 1.24s
91:	learn: 5.3916187	total: 128ms	remaining: 1.26s
92:	learn: 5.3807666	total: 129ms	remaining: 1.26s
93:	learn: 5.3722072	total: 130ms	remaining: 1.25s
94:	learn: 5.3629188	total: 131ms	remaining: 1.25s
95:	learn: 5.3482923	total: 132ms	remaining: 1.24s
96:	learn: 5.3397723	total: 132ms	remaining: 1.23s
97:	learn: 5.3315160	total: 133ms	remaining: 1.23s
98:	learn: 5.3238616	total: 134ms	remaining: 1.22s
99:	learn: 5.3132773	total: 135ms	remaining: 1.21s
100:	learn: 5.3068563	total: 135ms	remaining: 1.2s
101:	learn: 5.2965206	total: 136ms	remaining: 1.2s
102:	learn: 5.2883508	total: 137ms	remaining: 1.19s
103:	learn: 5.2799335	total: 137ms	remaining: 1.18s
104:	learn: 5.2717891	total: 138ms	remaining: 1.18s
105:	learn: 5.2626847	total: 153ms	remaining: 1.29s
106:	learn: 5.2516198	total: 155ms	remaining: 1.3s
107:	learn: 5.2410122	total: 160ms	remaining: 1.32s
108:	learn: 5.2326840	total: 162ms	remaining: 1.32s
109:	learn: 5.2242671	total: 163ms	remaining: 1.32s
110:	learn: 5.2163250	total: 164ms	remaining: 1.31s
111:	learn: 5.2111025	total: 164ms	remaining: 1.3s
112:	learn: 5.2063643	total: 165ms	remaining: 1.3s
113:	learn: 5.1969376	total: 166ms	remaining: 1.29s
114:	learn: 5.1907460	total: 167ms	remaining: 1.28s
115:	learn: 5.1818852	total: 167ms	remaining: 1.27s
116:	learn: 5.1782936	total: 168ms	remaining: 1.26s
117:	learn: 5.1709914	total: 170ms	remaining: 1.27s
118:	learn: 5.1662572	total: 172ms	remaining: 1.27s
119:	learn: 5.1614212	total: 174ms	remaining: 1.28s
120:	learn: 5.1582235	total: 178ms	remaining: 1.29s
121:	learn: 5.1547099	total: 183ms	remaining: 1.32s
122:	learn: 5.1463881	total: 186ms	remaining: 1.32s
123:	learn: 5.1395294	total: 187ms	remaining: 1.32s
124:	learn: 5.1342760	total: 188ms	remaining: 1.31s
125:	learn: 5.1285361	total: 189ms	remaining: 1.31s
126:	learn: 5.1233004	total: 192ms	remaining: 1.32s
127:	learn: 5.1162005	total: 194ms	remaining: 1.32s
128:	learn: 5.1087287	total: 197ms	remaining: 1.33s
129:	learn: 5.1040759	total: 198ms	remaining: 1.32s
130:	learn: 5.1003176	total: 200ms	remaining: 1.32s
131:	learn: 5.0958142	total: 201ms	remaining: 1.32s
132:	learn: 5.0921469	total: 203ms	remaining: 1.32s
133:	learn: 5.0852583	total: 205ms	remaining: 1.32s
134:	learn: 5.0792194	total: 206ms	remaining: 1.32s
135:	learn: 5.0764768	total: 207ms	remaining: 1.31s
136:	learn: 5.0721339	total: 208ms	remaining: 1.31s
137:	learn: 5.0670316	total: 210ms	remaining: 1.31s
138:	learn: 5.0613583	total: 211ms	remaining: 1.31s
139:	learn: 5.0567591	total: 213ms	remaining: 1.31s
140:	learn: 5.0502540	total: 217ms	remaining: 1.32s
141:	learn: 5.0483765	total: 217ms	remaining: 1.31s
142:	learn: 5.0426038	total: 218ms	remaining: 1.31s
143:	learn: 5.0374773	total: 219ms	remaining: 1.3s
144:	learn: 5.0323049	total: 222ms	remaining: 1.31s
145:	learn: 5.0259762	total: 224ms	remaining: 1.31s
146:	learn: 5.0195245	total: 226ms	remaining: 1.31s
147:	learn: 5.0175694	total: 228ms	remaining: 1.31s
148:	learn: 5.0089624	total: 229ms	remaining: 1.31s
149:	learn: 5.0038803	total: 230ms	remaining: 1.3s
150:	learn: 4.9963876	total: 232ms	remaining: 1.3s
151:	learn: 4.9933617	total: 233ms	remaining: 1.3s
152:	learn: 4.9900575	total: 236ms	remaining: 1.3s
153:	learn: 4.9869088	total: 239ms	remaining: 1.31s
154:	learn: 4.9852072	total: 240ms	remaining: 1.31s
155:	learn: 4.9790035	total: 241ms	remaining: 1.3s
156:	learn: 4.9731422	total: 242ms	remaining: 1.3s
157:	learn: 4.9670567	total: 244ms	remaining: 1.3s
158:	learn: 4.9614607	total: 245ms	remaining: 1.29s
159:	learn: 4.9542404	total: 246ms	remaining: 1.29s
160:	learn: 4.9523207	total: 246ms	remaining: 1.28s
161:	learn: 4.9483378	total: 247ms	remaining: 1.28s
162:	learn: 4.9432286	total: 249ms	remaining: 1.28s
163:	learn: 4.9385458	total: 251ms	remaining: 1.28s
164:	learn: 4.9353306	total: 253ms	remaining: 1.28s
165:	learn: 4.9320515	total: 255ms	remaining: 1.28s
166:	learn: 4.9289642	total: 256ms	remaining: 1.27s
167:	learn: 4.9228602	total: 257ms	remaining: 1.27s
168:	learn: 4.9176688	total: 258ms	remaining: 1.27s
169:	learn: 4.9103654	total: 259ms	remaining: 1.27s
170:	learn: 4.9064572	total: 260ms	remaining: 1.26s
171:	learn: 4.9019965	total: 261ms	remaining: 1.25s
172:	learn: 4.8968162	total: 262ms	remaining: 1.25s
173:	learn: 4.8911231	total: 265ms	remaining: 1.26s
174:	learn: 4.8876302	total: 266ms	remaining: 1.25s
175:	learn: 4.8852597	total: 267ms	remaining: 1.25s
176:	learn: 4.8806597	total: 268ms	remaining: 1.25s
177:	learn: 4.8772997	total: 270ms	remaining: 1.25s
178:	learn: 4.8740388	total: 271ms	remaining: 1.24s
179:	learn: 4.8694370	total: 272ms	remaining: 1.24s
180:	learn: 4.8612687	total: 272ms	remaining: 1.23s
181:	learn: 4.8586731	total: 273ms	remaining: 1.23s
182:	learn: 4.8540362	total: 277ms	remaining: 1.24s
183:	learn: 4.8513024	total: 279ms	remaining: 1.24s
184:	learn: 4.8475101	total: 280ms	remaining: 1.23s
185:	learn: 4.8456917	total: 281ms	remaining: 1.23s
186:	learn: 4.8420586	total: 282ms	remaining: 1.23s
187:	learn: 4.8386237	total: 285ms	remaining: 1.23s
188:	learn: 4.8346022	total: 286ms	remaining: 1.23s
189:	learn: 4.8308590	total: 289ms	remaining: 1.23s
190:	learn: 4.8275905	total: 293ms	remaining: 1.24s
191:	learn: 4.8222462	total: 294ms	remaining: 1.24s
192:	learn: 4.8166864	total: 295ms	remaining: 1.23s
193:	learn: 4.8147971	total: 298ms	remaining: 1.24s
194:	learn: 4.8116394	total: 299ms	remaining: 1.23s
195:	learn: 4.8048134	total: 299ms	remaining: 1.23s
196:	learn: 4.8025161	total: 306ms	remaining: 1.25s
197:	learn: 4.8000879	total: 308ms	remaining: 1.25s
198:	learn: 4.7947731	total: 309ms	remaining: 1.25s
199:	learn: 4.7916648	total: 311ms	remaining: 1.24s
200:	learn: 4.7859899	total: 313ms	remaining: 1.24s
201:	learn: 4.7823871	total: 313ms	remaining: 1.24s
202:	learn: 4.7786237	total: 314ms	remaining: 1.23s
203:	learn: 4.7757722	total: 316ms	remaining: 1.23s
204:	learn: 4.7702310	total: 324ms	remaining: 1.25s
205:	learn: 4.7644967	total: 327ms	remaining: 1.26s
206:	learn: 4.7631387	total: 328ms	remaining: 1.25s
207:	learn: 4.7580533	total: 328ms	remaining: 1.25s
208:	learn: 4.7550638	total: 331ms	remaining: 1.25s
209:	learn: 4.7524653	total: 337ms	remaining: 1.27s
210:	learn: 4.7480674	total: 338ms	remaining: 1.26s
211:	learn: 4.7441633	total: 339ms	remaining: 1.26s
212:	learn: 4.7366709	total: 341ms	remaining: 1.26s
213:	learn: 4.7334926	total: 342ms	remaining: 1.25s
214:	learn: 4.7318646	total: 344ms	remaining: 1.26s
215:	learn: 4.7283983	total: 345ms	remaining: 1.25s
216:	learn: 4.7238660	total: 346ms	remaining: 1.25s
217:	learn: 4.7234834	total: 349ms	remaining: 1.25s
218:	learn: 4.7209542	total: 353ms	remaining: 1.26s
219:	learn: 4.7161734	total: 355ms	remaining: 1.26s
220:	learn: 4.7105640	total: 358ms	remaining: 1.26s
221:	learn: 4.7071603	total: 361ms	remaining: 1.26s
222:	learn: 4.7040835	total: 363ms	remaining: 1.26s
223:	learn: 4.7025018	total: 364ms	remaining: 1.26s
224:	learn: 4.7002697	total: 365ms	remaining: 1.26s
225:	learn: 4.6953463	total: 366ms	remaining: 1.25s
226:	learn: 4.6897693	total: 367ms	remaining: 1.25s
227:	learn: 4.6879195	total: 368ms	remaining: 1.25s
228:	learn: 4.6829821	total: 369ms	remaining: 1.24s
229:	learn: 4.6795787	total: 370ms	remaining: 1.24s
230:	learn: 4.6757514	total: 371ms	remaining: 1.23s
231:	learn: 4.6727107	total: 373ms	remaining: 1.23s
232:	learn: 4.6690533	total: 375ms	remaining: 1.23s
233:	learn: 4.6675957	total: 376ms	remaining: 1.23s
234:	learn: 4.6642413	total: 377ms	remaining: 1.23s
235:	learn: 4.6622470	total: 378ms	remaining: 1.22s
236:	learn: 4.6586684	total: 379ms	remaining: 1.22s
237:	learn: 4.6580176	total: 379ms	remaining: 1.21s
238:	learn: 4.6576567	total: 380ms	remaining: 1.21s
239:	learn: 4.6532429	total: 380ms	remaining: 1.2s
240:	learn: 4.6507302	total: 383ms	remaining: 1.21s
241:	learn: 4.6476713	total: 384ms	remaining: 1.2s
242:	learn: 4.6455060	total: 389ms	remaining: 1.21s
243:	learn: 4.6412979	total: 391ms	remaining: 1.21s
244:	learn: 4.6379811	total: 392ms	remaining: 1.21s
245:	learn: 4.6350623	total: 394ms	remaining: 1.21s
246:	learn: 4.6316060	total: 394ms	remaining: 1.2s
247:	learn: 4.6302155	total: 395ms	remaining: 1.2s
248:	learn: 4.6272981	total: 396ms	remaining: 1.19s
249:	learn: 4.6246918	total: 397ms	remaining: 1.19s
250:	learn: 4.6218401	total: 398ms	remaining: 1.19s
251:	learn: 4.6196021	total: 398ms	remaining: 1.18s
252:	learn: 4.6135840	total: 404ms	remaining: 1.19s
253:	learn: 4.6119388	total: 407ms	remaining: 1.19s
254:	learn: 4.6087070	total: 408ms	remaining: 1.19s
255:	learn: 4.6047716	total: 408ms	remaining: 1.19s
256:	learn: 4.6042313	total: 409ms	remaining: 1.18s
257:	learn: 4.6007504	total: 410ms	remaining: 1.18s
258:	learn: 4.5964883	total: 411ms	remaining: 1.18s
259:	learn: 4.5947078	total: 412ms	remaining: 1.17s
260:	learn: 4.5888180	total: 413ms	remaining: 1.17s
261:	learn: 4.5850542	total: 413ms	remaining: 1.16s
262:	learn: 4.5814714	total: 416ms	remaining: 1.17s
263:	learn: 4.5775552	total: 418ms	remaining: 1.16s
264:	learn: 4.5745714	total: 419ms	remaining: 1.16s
265:	learn: 4.5730292	total: 419ms	remaining: 1.16s
266:	learn: 4.5713262	total: 420ms	remaining: 1.15s
267:	learn: 4.5710192	total: 421ms	remaining: 1.15s
268:	learn: 4.5657666	total: 422ms	remaining: 1.15s
269:	learn: 4.5633835	total: 423ms	remaining: 1.14s
270:	learn: 4.5581658	total: 424ms	remaining: 1.14s
271:	learn: 4.5562921	total: 425ms	remaining: 1.14s
272:	learn: 4.5493838	total: 426ms	remaining: 1.13s
273:	learn: 4.5462275	total: 426ms	remaining: 1.13s
274:	learn: 4.5406210	total: 428ms	remaining: 1.13s
275:	learn: 4.5328982	total: 430ms	remaining: 1.13s
276:	learn: 4.5297574	total: 431ms	remaining: 1.13s
277:	learn: 4.5257929	total: 432ms	remaining: 1.12s
278:	learn: 4.5215722	total: 433ms	remaining: 1.12s
279:	learn: 4.5188181	total: 434ms	remaining: 1.11s
280:	learn: 4.5140123	total: 435ms	remaining: 1.11s
281:	learn: 4.5083314	total: 435ms	remaining: 1.11s
282:	learn: 4.5060385	total: 436ms	remaining: 1.1s
283:	learn: 4.5058056	total: 436ms	remaining: 1.1s
284:	learn: 4.5015504	total: 437ms	remaining: 1.1s
285:	learn: 4.4946926	total: 438ms	remaining: 1.09s
286:	learn: 4.4893302	total: 438ms	remaining: 1.09s
287:	learn: 4.4848270	total: 439ms	remaining: 1.08s
288:	learn: 4.4782854	total: 441ms	remaining: 1.09s
289:	learn: 4.4753117	total: 445ms	remaining: 1.09s
290:	learn: 4.4715813	total: 446ms	remaining: 1.09s
291:	learn: 4.4691650	total: 447ms	remaining: 1.08s
292:	learn: 4.4620680	total: 448ms	remaining: 1.08s
293:	learn: 4.4585410	total: 451ms	remaining: 1.08s
294:	learn: 4.4557575	total: 452ms	remaining: 1.08s
295:	learn: 4.4530274	total: 453ms	remaining: 1.08s
296:	learn: 4.4506593	total: 455ms	remaining: 1.08s
297:	learn: 4.4446969	total: 460ms	remaining: 1.08s
298:	learn: 4.4420528	total: 461ms	remaining: 1.08s
299:	learn: 4.4400368	total: 463ms	remaining: 1.08s
300:	learn: 4.4350171	total: 464ms	remaining: 1.08s
301:	learn: 4.4299621	total: 465ms	remaining: 1.07s
302:	learn: 4.4276663	total: 477ms	remaining: 1.1s
303:	learn: 4.4250300	total: 477ms	remaining: 1.09s
304:	learn: 4.4225888	total: 478ms	remaining: 1.09s
305:	learn: 4.4189367	total: 479ms	remaining: 1.08s
306:	learn: 4.4168880	total: 479ms	remaining: 1.08s
307:	learn: 4.4137734	total: 480ms	remaining: 1.08s
308:	learn: 4.4111294	total: 481ms	remaining: 1.07s
309:	learn: 4.4085082	total: 481ms	remaining: 1.07s
310:	learn: 4.4048803	total: 482ms	remaining: 1.07s
311:	learn: 4.4045938	total: 483ms	remaining: 1.06s
312:	learn: 4.4021399	total: 483ms	remaining: 1.06s
313:	learn: 4.4002847	total: 484ms	remaining: 1.06s
314:	learn: 4.3958055	total: 485ms	remaining: 1.05s
315:	learn: 4.3928388	total: 485ms	remaining: 1.05s
316:	learn: 4.3892131	total: 488ms	remaining: 1.05s
317:	learn: 4.3861981	total: 489ms	remaining: 1.05s
318:	learn: 4.3850542	total: 490ms	remaining: 1.04s
319:	learn: 4.3793646	total: 491ms	remaining: 1.04s
320:	learn: 4.3783876	total: 491ms	remaining: 1.04s
321:	learn: 4.3758167	total: 492ms	remaining: 1.04s
322:	learn: 4.3746002	total: 493ms	remaining: 1.03s
323:	learn: 4.3709890	total: 493ms	remaining: 1.03s
324:	learn: 4.3674185	total: 494ms	remaining: 1.03s
325:	learn: 4.3635846	total: 495ms	remaining: 1.02s
326:	learn: 4.3607707	total: 495ms	remaining: 1.02s
327:	learn: 4.3586758	total: 499ms	remaining: 1.02s
328:	learn: 4.3542282	total: 501ms	remaining: 1.02s
329:	learn: 4.3537734	total: 504ms	remaining: 1.02s
330:	learn: 4.3516480	total: 505ms	remaining: 1.02s
331:	learn: 4.3482099	total: 506ms	remaining: 1.02s
332:	learn: 4.3458527	total: 508ms	remaining: 1.02s
333:	learn: 4.3423734	total: 509ms	remaining: 1.01s
334:	learn: 4.3408144	total: 511ms	remaining: 1.01s
335:	learn: 4.3397071	total: 512ms	remaining: 1.01s
336:	learn: 4.3354308	total: 513ms	remaining: 1.01s
337:	learn: 4.3352189	total: 516ms	remaining: 1.01s
338:	learn: 4.3285072	total: 518ms	remaining: 1.01s
339:	learn: 4.3261407	total: 519ms	remaining: 1.01s
340:	learn: 4.3237856	total: 520ms	remaining: 1s
341:	learn: 4.3206325	total: 522ms	remaining: 1s
342:	learn: 4.3197372	total: 523ms	remaining: 1s
343:	learn: 4.3180009	total: 525ms	remaining: 1s
344:	learn: 4.3127136	total: 526ms	remaining: 999ms
345:	learn: 4.3082208	total: 538ms	remaining: 1.02s
346:	learn: 4.3058909	total: 539ms	remaining: 1.01s
347:	learn: 4.3051379	total: 540ms	remaining: 1.01s
348:	learn: 4.3047872	total: 542ms	remaining: 1.01s
349:	learn: 4.3035013	total: 548ms	remaining: 1.02s
350:	learn: 4.3029381	total: 550ms	remaining: 1.02s
351:	learn: 4.2995485	total: 552ms	remaining: 1.01s
352:	learn: 4.2947684	total: 553ms	remaining: 1.01s
353:	learn: 4.2945815	total: 555ms	remaining: 1.01s
354:	learn: 4.2925516	total: 556ms	remaining: 1.01s
355:	learn: 4.2886289	total: 561ms	remaining: 1.01s
356:	learn: 4.2878028	total: 564ms	remaining: 1.01s
357:	learn: 4.2845669	total: 565ms	remaining: 1.01s
358:	learn: 4.2789023	total: 566ms	remaining: 1.01s
359:	learn: 4.2769380	total: 567ms	remaining: 1.01s
360:	learn: 4.2734251	total: 574ms	remaining: 1.01s
361:	learn: 4.2697265	total: 575ms	remaining: 1.01s
362:	learn: 4.2655659	total: 576ms	remaining: 1.01s
363:	learn: 4.2621172	total: 578ms	remaining: 1.01s
364:	learn: 4.2591851	total: 579ms	remaining: 1.01s
365:	learn: 4.2576685	total: 583ms	remaining: 1.01s
366:	learn: 4.2534324	total: 586ms	remaining: 1.01s
367:	learn: 4.2502167	total: 587ms	remaining: 1.01s
368:	learn: 4.2451483	total: 589ms	remaining: 1.01s
369:	learn: 4.2440158	total: 590ms	remaining: 1s
370:	learn: 4.2403292	total: 591ms	remaining: 1s
371:	learn: 4.2367180	total: 593ms	remaining: 1s
372:	learn: 4.2334959	total: 599ms	remaining: 1.01s
373:	learn: 4.2303575	total: 600ms	remaining: 1s
374:	learn: 4.2273812	total: 602ms	remaining: 1s
375:	learn: 4.2261691	total: 605ms	remaining: 1s
376:	learn: 4.2259639	total: 606ms	remaining: 1s
377:	learn: 4.2243465	total: 608ms	remaining: 1s
378:	learn: 4.2225954	total: 613ms	remaining: 1s
379:	learn: 4.2197009	total: 615ms	remaining: 1s
380:	learn: 4.2163562	total: 616ms	remaining: 1s
381:	learn: 4.2143265	total: 619ms	remaining: 1s
382:	learn: 4.2129014	total: 620ms	remaining: 999ms
383:	learn: 4.2113311	total: 621ms	remaining: 997ms
384:	learn: 4.2086248	total: 623ms	remaining: 995ms
385:	learn: 4.2046591	total: 626ms	remaining: 996ms

In [ ]:
y_

In [27]:
list(models.values())

[LinearRegression(),
 Lasso(),
 Ridge(),
 AdaBoostRegressor(),
 CatBoostRegressor(loss_function='RMSE'),
 XGBRegressor(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...),
 KNeighborsRegressor(),
 DecisionTreeRegressor(),
 RandomForestRegressor()]

In [25]:
model

RandomForestRegressor()